version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails s -b '0.0.0.0'"
    container_name: employee_feedback
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: employee_feedback
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_feedback_development

volumes:
  postgres_data:
